spring:
  profiles:
    active: local  # 기본 프로파일을 prod로 설정

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/AutoSEWORLD?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 7562
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  server:
    port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/AutoSEWORLD?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 7562
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  server:
    port: 8080
